// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crossprod_cpp
arma::mat crossprod_cpp(const arma::mat& X);
RcppExport SEXP _faststats_crossprod_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprod_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// cov_wt_cpp
List cov_wt_cpp(const arma::mat& x, Rcpp::Nullable<Rcpp::NumericVector> wt_, bool cor, Rcpp::Nullable<Rcpp::NumericVector> center_, std::string method);
RcppExport SEXP _faststats_cov_wt_cpp(SEXP xSEXP, SEXP wt_SEXP, SEXP corSEXP, SEXP center_SEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type wt_(wt_SEXP);
    Rcpp::traits::input_parameter< bool >::type cor(corSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type center_(center_SEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_wt_cpp(x, wt_, cor, center_, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_faststats_crossprod_cpp", (DL_FUNC) &_faststats_crossprod_cpp, 1},
    {"_faststats_cov_wt_cpp", (DL_FUNC) &_faststats_cov_wt_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_faststats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
