# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_cpp <- function(X) {
    .Call(`_faststats_crossprod_cpp`, X)
}

cov_wt_cpp <- function(x, wt_ = NULL, cor = FALSE, center_ = NULL, method = "unbiased") {
    .Call(`_faststats_cov_wt_cpp`, x, wt_, cor, center_, method)
}

